### ISSUE TITLE
If email is nonexistent there is an exception thrown.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/tbphpmailer#2]
When I make test orders I go  and create dummy profiles/guest with emails like asfadfdfd@asdasd.asd

If I use this module and the domain is not correct I get Error 500 in FO and the following exception:

![image](https://user-images.githubusercontent.com/11251370/233203849-884dd795-cde3-4fd2-b414-44b4f7ce399d.png)

If enter a wrong email (misspelled part of it) it will end up with the same FO error which is not perfect for conversions.

Also the same exception arises when the status of such order is changed.

Best solution will be to ignore such errors or have the current behaviour up until now where the server sends the email but it bounces back to the inbox and no trace is left in TB.

**Comment by getdatakick** [comment]
This should be handled in core. Thirty bees core should expect that MailTransport implementation will throw something, and handle it correctly.

Commit implements this: thirtybees/thirtybees@7d07228506d768b789fc28b5679f8742f57e2e63
